// colors.ts
export default {
  PRIMARY_COLOR: '#5A9DF6',
  SECONDARY_COLOR: '#34495E',
  BACKGROUND_COLOR: '#FFFFFF',
  TEXT_COLOR: '#2C3E50',
  TEXT_COLOR_LIGHT: '#7F8C8D',
  ACCENT_COLOR: '#F39C12',
  SUCCESS_COLOR: '#27AE60',
  ERROR_COLOR: '#E74C3C',
  WARNING_COLOR: '#F1C40F',
  INFO_COLOR: '#3498DB',
  INPUT_BACKGROUND_COLOR: '#EBEEF0',
  INPUT_BORDER_COLOR: '#D6DBDF',
};
